//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTap.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;
    
    

    public partial class HoiVien 
    {
        public System.Guid APK { get; set; }
        [Required]
        public string DivisionID { get; set; }
       
        public string MemberID { get; set; }
        
        public string MemberName { get; set; }
        public string ShortName { get; set; }
        public string Address { get; set; }
        public string Identify { get; set; }
        public string Phone { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Website { get; set; }
        public string Mailbox { get; set; }
        public string AreaName { get; set; }
        public string CityName { get; set; }
        public string CountryName { get; set; }
        public string WardName { get; set; }
        public Nullable<System.DateTime> CreatDate { get; set; }
        public string CreateUserID { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public string LastModifyUserID { get; set; }
        public byte Disabled { get; set; }
    }
}
