//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuChild2
    {
        public string Child2_id { get; set; }
        public string Child1_id { get; set; }
        public string Child2_Name { get; set; }
        public Nullable<bool> Action { get; set; }
    }
}
