---- Tạo bảng Đơn vị - AT1101

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[AT1101]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[AT1101](
	[APK] uniqueidentifier NULL DEFAULT (newid()),
	[DivisionID] nvarchar(5) NOT NULL,
	[DivisionName] nvarchar(250) NULL,
	[Disabled] tinyint NOT NULL CONSTRAINT [DF_AT1101_Disabled]  DEFAULT ((0)),
	[Tel] nvarchar(100) NULL,
	[Fax] nvarchar(100) NULL,
	[Email] nvarchar(100) NULL,
	[Address] nvarchar(250) NULL,
	[ContactPerson] nvarchar(100) NULL,
	[VATNO] nvarchar(50) NULL,
	[BeginMonth] int NULL,
	[BeginYear] int NULL,
	[CreateDate] datetime NULL,
	[CreateUserID] nvarchar(50) NULL,
	[LastModifyDate] datetime NULL,
	[LastModifyUserID] nvarchar(50) NULL,
	[DivisionNameE] nvarchar(250) NULL,
	[AddressE] nvarchar(250) NULL,
	[ImageLogo] ntext NULL,
	[Logo] image NULL,
	[TaxAgentCertificate] nvarchar(250) NULL,
	[TaxAgentContractDate] datetime NULL,
	[TaxAgentFax] nvarchar(100) NULL,
	[TaxAgentTel] nvarchar(250) NULL,
	[TaxAgentEmail] nvarchar(250) NULL,
	[TaxAgentPerson] nvarchar(250) NULL,
	[TaxAgentContractNo] nvarchar(250) NULL,
	[TaxAgentCity] nvarchar(250) NULL,
	[TaxAgentDistrict] nvarchar(250) NULL,
	[TaxAgentAddress] nvarchar(250) NULL,
	[TaxAgentName] nvarchar(250) NULL,
	[TaxAgentNo] nvarchar(250) NULL,
	[IsUseTaxAgent] tinyint NULL,
	[ManagingUnitTaxNo] nvarchar(250) NULL,
	[ManagingUnit] nvarchar(250) NULL,
	[TaxDepartID] varchar(50) NULL,
	[TaxDepartmentID] varchar(50) NULL,
	[TaxreturnPerson] nvarchar(250) NULL,
	[FiscalBeginDate] nvarchar(50) NULL,
	[District] nvarchar(250) NULL,
	[City] nvarchar(250) NULL,
	[Industry] nvarchar(500) NULL,
	[StartDate] datetime NULL DEFAULT ('01/01/1900'),
	[EndDate] datetime NULL DEFAULT ('12/31/1900'),
	[PeriodNum] int NULL DEFAULT ((12)),
	[BaseCurrencyID] varchar(50) NULL,
	[BankAccountID] varchar(50) NULL,
	[QuantityDecimals] tinyint NULL DEFAULT ((0)),
	[UnitCostDecimals] tinyint NULL DEFAULT ((0)),
	[ConvertedDecimals] tinyint NULL DEFAULT ((0)),
	[PercentDecimal] tinyint NULL DEFAULT ((0)),
	[WareHouseID] varchar(50) NULL,
	[WareHouseTempID] varchar(50) NULL,
	[IsCheckinDistance] tinyint NULL DEFAULT ((1)),
	[CheckinDistance] int NULL DEFAULT ((50)),
	[IsCheckinImage] tinyint NULL DEFAULT ((0)),
	[ImageResolution] tinyint NULL DEFAULT ((0)),
	[MaxImageQuantity] tinyint NULL DEFAULT ((5)),
	[IsEnableSaleManLocation] tinyint NULL DEFAULT ((1)),
	[ParentDivisionID] varchar(50) NULL,
 CONSTRAINT [PK_AT1101] PRIMARY KEY NONCLUSTERED 
(
	[DivisionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END