---- Create by Đào Tấn Đạt on 2/23/2018 6:15:07 PM
---- Chi tiết Hợp đồng

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CRMT2001]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[CRMT2001]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NULL,
  [DivisionID] NVARCHAR(50) NOT NULL,
  [TransactionID] NVARCHAR(50) NOT NULL,
  [ContractID] NVARCHAR(50) NOT NULL,
  [InventoryID] NVARCHAR(50) NULL,
  [SOrderType] TINYINT DEFAULT (0) NULL,
  [OrderQuantity] DECIMAL(28,8) NULL,
  [SalePrice] DECIMAL(28,8) NULL,
  [OriginalAmount] DECIMAL(28,8) NULL,
  [ConvertedAmount] DECIMAL(28,8) NULL,
  [Description] NVARCHAR(250) NULL,
  [Ana01ID] NVARCHAR(50) NULL,
  [Ana02ID] NVARCHAR(50) NULL,
  [Ana03ID] NVARCHAR(50) NULL,
  [Ana04ID] NVARCHAR(50) NULL,
  [Ana05ID] NVARCHAR(50) NULL,
  [VATGroupID] NVARCHAR(50) NULL,
  [VATOriginalAmount] DECIMAL(28,8) NULL,
  [VATConvertedAmount] DECIMAL(28,8) NULL,
  [VATPercent] DECIMAL(28,8) NULL
CONSTRAINT [PK_CRMT2001] PRIMARY KEY CLUSTERED
(
  [DivisionID],
  [TransactionID]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END