--------------------------------------------------------------------------------------------------------------
--
-- TEST
--
--------------------------------------------------------------------------------------------------------------
--IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_DTTDBInI_MTTDBIn]') AND parent_object_id = OBJECT_ID(N'[dbo].[DTTDBInI]'))
--ALTER TABLE [dbo].[DTTDBInI] DROP CONSTRAINT [FK_DTTDBInI_MTTDBIn]
--GO

--IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_DTTDBInI_DMVT]') AND parent_object_id = OBJECT_ID(N'[dbo].[DTTDBInI]'))
--ALTER TABLE [dbo].[DTTDBInI] DROP CONSTRAINT [FK_DTTDBInI_DMVT]
--GO

--IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DTTDBInI]') AND type in (N'U'))
--DROP TABLE [dbo].[DTTDBInI]
--GO

--IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_DTTDBInII_MTTDBIn]') AND parent_object_id = OBJECT_ID(N'[dbo].[DTTDBInII]'))
--ALTER TABLE [dbo].[DTTDBInII] DROP CONSTRAINT [FK_DTTDBInII_MTTDBIn]
--GO

--IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_DTTDBInII_DMVT1]') AND parent_object_id = OBJECT_ID(N'[dbo].[DTTDBInII]'))
--ALTER TABLE [dbo].[DTTDBInII] DROP CONSTRAINT [FK_DTTDBInII_DMVT1]
--GO

--IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_DTTDBInII_DMVT2]') AND parent_object_id = OBJECT_ID(N'[dbo].[DTTDBInII]'))
--ALTER TABLE [dbo].[DTTDBInII] DROP CONSTRAINT [FK_DTTDBInII_DMVT2]
--GO

--IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DTTDBInII]') AND type in (N'U'))
--DROP TABLE [dbo].[DTTDBInII]
--GO

--IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MTTDBIn]') AND type in (N'U'))
--DROP TABLE [dbo].[MTTDBIn]
--GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MTTDBIn]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[MTTDBIn](
	[MTTDBInID] [uniqueidentifier] NOT NULL,
	[Stt] [int] IDENTITY(1,1) NOT NULL,
	[KyBKMVTTDB] [int] NOT NULL,
	[NgayBKMVTTDB] [smalldatetime] NOT NULL,
	[NamBKMVTTDB] [int] NOT NULL,
	[DienGiai] [nvarchar](128) NULL,
	[MaNT] [varchar](16) NULL,
	[TyGia] [decimal](20, 6) NULL,
	[ITotal7NT] [decimal](20, 6) NULL,
	[ITotal7] [decimal](20, 6) NULL,
	[ITotal9NT] [decimal](20, 6) NULL,
	[ITotal9] [decimal](20, 6) NULL,
	[ITotal10NT] [decimal](20, 6) NULL,
	[ITotal10] [decimal](20, 6) NULL,
	[IITotal7NT] [decimal](20, 6) NULL,
	[IITotal7] [decimal](20, 6) NULL,
 CONSTRAINT [PK_MTTDBIn] PRIMARY KEY CLUSTERED 
(
	[MTTDBInID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[MTTDBIn]  WITH CHECK ADD  CONSTRAINT [FK_MTTDBIn_DMNT] FOREIGN KEY([MaNT])
REFERENCES [dbo].[DMNT] ([MaNT])
ALTER TABLE [dbo].[MTTDBIn] CHECK CONSTRAINT [FK_MTTDBIn_DMNT]

ALTER TABLE [dbo].[MTTDBIn] ADD  CONSTRAINT [DF_MTTDBIn_MaNT]  DEFAULT ('VND') FOR [MaNT]
ALTER TABLE [dbo].[MTTDBIn] ADD  CONSTRAINT [DF_MTTDBIn_ITotal7NT]  DEFAULT ('0') FOR [ITotal7NT]
ALTER TABLE [dbo].[MTTDBIn] ADD  CONSTRAINT [DF_MTTDBIn_ITotal7]  DEFAULT ('0') FOR [ITotal7]
ALTER TABLE [dbo].[MTTDBIn] ADD  CONSTRAINT [DF_MTTDBIn_ITotal9NT]  DEFAULT ('0') FOR [ITotal9NT]
ALTER TABLE [dbo].[MTTDBIn] ADD  CONSTRAINT [DF_MTTDBIn_ITotal9]  DEFAULT ('0') FOR [ITotal9]
ALTER TABLE [dbo].[MTTDBIn] ADD  CONSTRAINT [DF_MTTDBIn_ITotal10NT]  DEFAULT ('0') FOR [ITotal10NT]
ALTER TABLE [dbo].[MTTDBIn] ADD  CONSTRAINT [DF_MTTDBIn_ITotal10]  DEFAULT ('0') FOR [ITotal10]
ALTER TABLE [dbo].[MTTDBIn] ADD  CONSTRAINT [DF_MTTDBIn_IITotal7NT]  DEFAULT ('0') FOR [IITotal7NT]
ALTER TABLE [dbo].[MTTDBIn] ADD  CONSTRAINT [DF_MTTDBIn_IITotal7]  DEFAULT ('0') FOR [IITotal7]
END

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DTTDBInI]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DTTDBInI](
	[DTTDBInIID] [uniqueidentifier] NOT NULL,
	[MTTDBInID] [uniqueidentifier] NOT NULL,
	[Stt] [int] IDENTITY(1,1) NOT NULL,
	[NgayHD] [smalldatetime] NULL,
	[NgayCt] [smalldatetime] NULL,
	[SoHoaDon] [nvarchar](128) NULL,
	[SoSeries] [nvarchar](128) NULL,
	[IMaVT5] [varchar](16) NULL,
	[ITenVT5] [nvarchar](128) NULL,
	[ISoLuong6] [decimal](20, 6) NULL,
	[Ips7NT] [decimal](20, 6) NULL,
	[Ips7] [decimal](20, 6) NULL,
	[IThueTTDB8NT] [decimal](20, 6) NULL,
	[IThueTTDB8] [decimal](20, 6) NULL,
	[Ips9NT] [decimal](20, 6) NULL,
	[Ips9] [decimal](20, 6) NULL,
	[Ips10NT] [decimal](20, 6) NULL,
	[Ips10] [decimal](20, 6) NULL,
 CONSTRAINT [PK_DTTDBInI] PRIMARY KEY CLUSTERED 
(
	[DTTDBInIID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[DTTDBInI]  WITH CHECK ADD  CONSTRAINT [FK_DTTDBInI_MTTDBIn] FOREIGN KEY([MTTDBInID])
REFERENCES [dbo].[MTTDBIn] ([MTTDBInID])
ALTER TABLE [dbo].[DTTDBInI] CHECK CONSTRAINT [FK_DTTDBInI_MTTDBIn]

ALTER TABLE [dbo].[DTTDBInI]  WITH CHECK ADD  CONSTRAINT [FK_DTTDBInI_DMVT] FOREIGN KEY([IMaVT5])
REFERENCES [dbo].[DMVT] ([MaVT])
ALTER TABLE [dbo].[DTTDBInI] CHECK CONSTRAINT [FK_DTTDBInI_DMVT]

ALTER TABLE [dbo].[DTTDBInI] ADD  CONSTRAINT [DF_DTTDBInI_ISoLuong6]  DEFAULT ('0') FOR [ISoLuong6]
ALTER TABLE [dbo].[DTTDBInI] ADD  CONSTRAINT [DF_DTTDBInI_Ips7NT]  DEFAULT ('0') FOR [Ips7NT]
ALTER TABLE [dbo].[DTTDBInI] ADD  CONSTRAINT [DF_DTTDBInI_Ips7]  DEFAULT ('0') FOR [Ips7]
ALTER TABLE [dbo].[DTTDBInI] ADD  CONSTRAINT [DF_DTTDBInI_IThueTTDB8NT]  DEFAULT ('0') FOR [IThueTTDB8NT]
ALTER TABLE [dbo].[DTTDBInI] ADD  CONSTRAINT [DF_DTTDBInI_IThueTTDB8]  DEFAULT ('0') FOR [IThueTTDB8]
ALTER TABLE [dbo].[DTTDBInI] ADD  CONSTRAINT [DF_DTTDBInI_Ips9NT]  DEFAULT ('0') FOR [Ips9NT]
ALTER TABLE [dbo].[DTTDBInI] ADD  CONSTRAINT [DF_DTTDBInI_Ips9]  DEFAULT ('0') FOR [Ips9]
ALTER TABLE [dbo].[DTTDBInI] ADD  CONSTRAINT [DF_DTTDBInI_Ips10NT]  DEFAULT ('0') FOR [Ips10NT]
ALTER TABLE [dbo].[DTTDBInI] ADD  CONSTRAINT [DF_DTTDBInI_Ips10]  DEFAULT ('0') FOR [Ips10]
END

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DTTDBInII]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DTTDBInII](
	[DTTDBInIIID] [uniqueidentifier] NOT NULL,
	[MTTDBInID] [uniqueidentifier] NOT NULL,
	[Stt] [int] IDENTITY(1,1) NOT NULL,
	[IIMaVT2] [varchar](16) NULL,
	[IITenVT2] [nvarchar](128) NULL,
	[IISoLuong3] [decimal](20, 6) NULL,
	[IIMaVT4] [varchar](16) NULL,
	[IITenVT4] [nvarchar](128) NULL,
	[IISoLuong5] [decimal](20, 6) NULL,	
	[IIThueTTDB6NT] [decimal](20, 6) NULL,
	[IIThueTTDB6] [decimal](20, 6) NULL,
	[IIps7NT] [decimal](20, 6) NULL,
	[IIps7] [decimal](20, 6) NULL,
 CONSTRAINT [PK_DTTDBInII] PRIMARY KEY CLUSTERED 
(
	[DTTDBInIIID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[DTTDBInII]  WITH CHECK ADD  CONSTRAINT [FK_DTTDBInII_MTTDBIn] FOREIGN KEY([MTTDBInID])
REFERENCES [dbo].[MTTDBIn] ([MTTDBInID])
ALTER TABLE [dbo].[DTTDBInII] CHECK CONSTRAINT [FK_DTTDBInII_MTTDBIn]

ALTER TABLE [dbo].[DTTDBInII]  WITH CHECK ADD  CONSTRAINT [FK_DTTDBInII_DMVT1] FOREIGN KEY([IIMaVT2])
REFERENCES [dbo].[DMVT] ([MaVT])
ALTER TABLE [dbo].[DTTDBInII] CHECK CONSTRAINT [FK_DTTDBInII_DMVT1]

ALTER TABLE [dbo].[DTTDBInII]  WITH CHECK ADD  CONSTRAINT [FK_DTTDBInII_DMVT2] FOREIGN KEY([IIMaVT4])
REFERENCES [dbo].[DMVT] ([MaVT])
ALTER TABLE [dbo].[DTTDBInII] CHECK CONSTRAINT [FK_DTTDBInII_DMVT2]

ALTER TABLE [dbo].[DTTDBInII] ADD  CONSTRAINT [DF_DTTDBInII_IISoLuong3]  DEFAULT ('0') FOR [IISoLuong3]
ALTER TABLE [dbo].[DTTDBInII] ADD  CONSTRAINT [DF_DTTDBInII_IISoLuong5]  DEFAULT ('0') FOR [IISoLuong5]
ALTER TABLE [dbo].[DTTDBInII] ADD  CONSTRAINT [DF_DTTDBInII_IIThueTTDB6NT]  DEFAULT ('0') FOR [IIThueTTDB6NT]
ALTER TABLE [dbo].[DTTDBInII] ADD  CONSTRAINT [DF_DTTDBInII_IIThueTTDB6]  DEFAULT ('0') FOR [IIThueTTDB6]
ALTER TABLE [dbo].[DTTDBInII] ADD  CONSTRAINT [DF_DTTDBInII_IIps7NT]  DEFAULT ('0') FOR [IIps7NT]
ALTER TABLE [dbo].[DTTDBInII] ADD  CONSTRAINT [DF_DTTDBInII_IIps7]  DEFAULT ('0') FOR [IIps7]
END
