
  ALTER TABLE [AS_CRM].[dbo].[CRMT20801] ADD RequestTypeID INT
  ALTER TABLE [AS_CRM].[dbo].[CRMT20801] ADD BugTypeID INT
  ALTER TABLE [AS_CRM].[dbo].[CRMT20801] ADD ProjectID INT
  ALTER TABLE [AS_CRM].[dbo].[CRMT20801] ADD DeadlineExpect DATETIME  
  ALTER TABLE [AS_CRM].[dbo].[CRMT20801] ADD CompleteDate DATETIME
  ALTER TABLE [AS_CRM].[dbo].[CRMT20801] ADD DurationTime Decimal
  ALTER TABLE [AS_CRM].[dbo].[CRMT20801] ADD RealTime Decimal


  
