---- Create by Cao Thị Phượng on 10/12/2017 5:54:21 PM
---- Người dùng theo dõi trong hệ thống

IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[ST0008]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [dbo].[ST0008]
(
  [APK] UNIQUEIDENTIFIER DEFAULT newid() NOT NULL,
  [DivisionID] VARCHAR(50) NOT NULL,
  [RelatedToID] VARCHAR(50) NOT NULL,
  [UserID] VARCHAR(50) NOT NULL,
  [ReleatedToTypeID] INT NULL,
  [CreateUserID] VARCHAR(50) NULL,
  [CreateDate] DATETIME NULL
CONSTRAINT [PK_ST0008] PRIMARY KEY CLUSTERED
(
  [APK]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
END